language: cpp
compiler: g++
sudo: true

before_install:
   - sudo apt-add-repository ppa:sonkun/sfml-development --yes
   - sudo apt update -qq

install:
   - sudo apt install libsfml-dev

before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # give xvfb some time to start

script:
   make
